apiVersion: v1
kind: Service
metadata:
  name: webdeploy
  labels:
    app: webdeploy
spec:
  ports:
  - port: 80
    nodePort: 30080
  selector:
    app: webdeploy
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  labels:
    app: webdeploy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: webdeploy
   labels:
     app: webdeploy
spec:
   selector:
     matchlabels:
         app: webdeploy
   replicas: 1
   template:
     metadata:
         labels:
            app: webdeploy
     spec:
         containers:
         -  image: httpd
            name: webdeploy
            ports:
            -  containerPort: 80
               name: webdeploy
            volumeMounts:
            -  name: webdeploy-pv
               mountPath: /usr/local/apache2/htdocs/
         volumes:
         -  name: webdeploy-pv
            persistentVolumeClaim:
               claimName: web-pvc

